name: Fetch Germany Weather

# Trigger workflow every 4 hours and allow manual trigger
on:
  schedule:
    - cron: "0 */4 * * *" # every 4 hours
  workflow_dispatch:

jobs:
  fetch_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary

      - name: Run main.py
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
        run: python main.py
